version: '3.8'

services:
    app:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: ./_docker/local/Dockerfile
        volumes:
            - "./:/app:delegated"
        working_dir: /app
        ports:
          - "80:80"
          - "24678:24678"
        networks:
          - app-network
        command: tail -f /dev/null

networks:
    app-network:
        driver: bridge
