# fly.toml app configuration file generated for izzy-and-jacks-wedding on 2023-10-31T20:11:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "izzy-and-jacks-wedding"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[build]
  dockerfile = "_docker/live/Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
